### ISSUE TITLE
Compass and Clock do not update when Quark Installed

### ISSUE THREAD

**Issue by radzo73** [KLjiana/CompassHUD#4]
## Mod Version
1.0.0
## MC/Forge Version
1.20.1-47.2.17 (Forge)
## Mods required to see issue
- Quark 1.20.1-4.0-460
  - Zeta 1.20.1-1.0-24 (dependency)
# Steps To Reproduce
1. In Quark's config, enable "Compasses Work Everywhere" under "Tweaks" (it's on by default)
2. Restart your game (if you had to enable it)

https://github.com/user-attachments/assets/3082cf69-1022-44ea-b5db-675318f8bbeb

**Comment by Kaguya154** [comment]
I think the main issue lies in quark. This mod simply called Compass for rendering, and quark modified it.  
Solving this problem will make this simple mod no longer simple, so I refuse to fix this issue for quark.  
While disable "Compasses Work Everywhere" under "Tweaks" working, l will write it in discribtion.
